jobs:
  build:
    name: Build on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup node modules
        run: npm ci
      - name: Build
        run: npm run build
name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
