jobs:
  build:
    name: Build on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup node modules
        run: npm ci
      - name: Build
        run: npm run build
      - continue-on-error: true
        id: difference
        name: Check difference
        run: |
          git add -N .
          git diff --name-only --exit-code
      - if: steps.difference.outcome == 'failure'
        name: Commit changes and push if necessary
        run: |
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git add .
          git commit --author=. -m ':robot: Build by GitHub Actions'
          git push
name: Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:
